var Aspects = [
{name:"Aer",	 		meaning:"Air", 		tier:0, parents:[]},
{name:"Alienis", 		meaning:"Alien", 	tier:5, parents:["Tenebrae", "Vacuos"]},
{name:"Aqua", 			meaning:"Water", 	tier:0, parents:[]},
{name:"Auram", 			meaning:"Aura", 	tier:2, parents:["Aer", "Potentia"]},
{name:"Aversio", 		meaning:"Weapon", 	tier:4, parents:["Perditio", "Spiritus"]},
{name:"Bestia", 		meaning:"Beast", 	tier:3, parents:["Motus", "Victus"]},
{name:"Cognitio", 		meaning:"Mind", 	tier:4, parents:["Ignis", "Spiritus"]},
{name:"Desiderium", 	meaning:"Greed", 	tier:5, parents:["Spiritus", "Vacuos"]},
{name:"Exanimis", 		meaning:"Undeath", 	tier:3, parents:["Mortuus", "Motus"]},
{name:"Fabrico", 		meaning:"Craft", 	tier:5, parents:["Instrumentum", "Permutatio"]},
{name:"Gelum", 			meaning:"Ice", 		tier:1, parents:["Ignis", "Perditio"]},
{name:"Herba", 			meaning:"Plant", 	tier:2, parents:["Terra", "Victus"]},
{name:"Humanus", 		meaning:"Human", 	tier:4, parents:["Spiritus", "Victus"]},
{name:"Ignis", 			meaning:"Fire", 	tier:0, parents:[]},
{name:"Instrumentum", 	meaning:"Tool", 	tier:3, parents:["Metallum", "Potentia"]},
{name:"Lux", 			meaning:"Light", 	tier:1, parents:["Aer", "Ignis"]},
{name:"Machina", 		meaning:"Machine", 	tier:5, parents:["Instrumentum", "Motus"]},
{name:"Metallum", 		meaning:"Metal", 	tier:1, parents:["Ordo", "Terra"]},
{name:"Mortuus", 		meaning:"Death", 	tier:1, parents:["Aqua", "Perditio"]},
{name:"Motus", 			meaning:"Movement", tier:1, parents:["Aer", "Ordo"]},
{name:"Ordo", 			meaning:"Order", 	tier:0, parents:[]},
{name:"Perditio", 		meaning:"Entropy", 	tier:0, parents:[]},
{name:"Permutatio", 	meaning:"Change", 	tier:1, parents:["Ordo", "Perditio"]},
{name:"Potentia", 		meaning:"Energy", 	tier:1, parents:["Ignis", "Ordo"]},
{name:"Praemunio", 		meaning:"Armor", 	tier:4, parents:["Spiritus", "Terra"]},
{name:"Sensus", 		meaning:"Sense", 	tier:4, parents:["Aer", "Spiritus"]},
{name:"Spiritus", 		meaning:"Spirit", 	tier:3, parents:["Mortuus", "Victus"]},
{name:"Tenebrae", 		meaning:"Darkness", tier:3, parents:["Lux", "Vacuos"]},
{name:"Terra", 			meaning:"Earth", 	tier:0, parents:[]},
{name:"Vacuos", 		meaning:"Void", 	tier:1, parents:["Aer", "Perditio"]},
{name:"Victus", 		meaning:"Life", 	tier:1, parents:["Aqua", "Terra"]},
{name:"Vinculum", 		meaning:"Trap", 	tier:2, parents:["Motus", "Perditio"]},
{name:"Vitium", 		meaning:"Flux", 	tier:2, parents:["Perditio", "Potentia"]},
{name:"Vitreus", 		meaning:"Crystal", 	tier:1, parents:["Aer", "Terra"]},
{name:"Volatus", 		meaning:"Flight", 	tier:2, parents:["Aer", "Motus"	]}
]